### PR TITLE
feature: Custom format function

### PR DESCRIPTION
**Pull request by kjvalencik**
Add the ability to set a custom format function similar to [`env_logger`](https://docs.rs/env_logger/0.8.1/env_logger/struct.Builder.html#method.format).

```rust
android_logger::init_once(
    Config::default()
        .with_min_level(log::Level::Trace)
        .format(|f, record| write!(f, "my_app: {}", record.args()))
)
```

This is also useful for adding side-effects. For example, sending a log as a [`trace`](https://github.com/tokio-rs/tracing).

```rust
android_logger::init_once(
    Config::default()
        .with_min_level(log::Level::Trace)
        .format(|f, record| {
            tracing_log::format_trace(record).map_err(|_| std::fmt::Error)?;
            write!(f, "my_app: {}", record.args())
        })
)
```

### CODE REVIEW

**Comment by kjvalencik** [comment]
@Nercury Anything I can do to help make this feature ready to merge? Cheers!

**Comment by Nercury** [comment]
Sorry, I have not noticed your PR because of github notification spam.
Looks good to me.

**Review by Nercury — APPROVED** [review]

**Comment by Nercury** [comment]
Can you also add info about this in docs?

**Comment by kjvalencik** [comment]
@Nercury Absolutely! https://github.com/Nercury/android_logger-rs/pull/38

**Pull request merged**
