### PR TITLE
add log4rs support

### PR DESCRIPTION
**Pull request by king6cong**

### CODE REVIEW

**Comment by Nercury** [comment]
Can you explain briefly how does this help to support `log4rs`?

**Comment by Nercury** [comment]
Reverting because of no explanation. It would be no trouble to add this change, we just need a reason why.

**Comment by king6cong** [comment]
Sorry for the late explanation.

android_logger::init_once is great, but can't play well with other loggers. (only one log implementation is allowed of the `log` crate). `log4rs` makes composing loggers easy, so I think we should provide a `Appender` implementation in android_logger.

```
use std;
use log::Log;
use android_logger::PlatformLogger;
static ANDROID_LOGGER: PlatformLogger = PlatformLogger;
use log4rs::append::Append;
use log::LogRecord;


#[derive(Debug)]
pub struct AndroidAppender {}

impl Append for AndroidAppender {
    fn append(&self,
              record: &LogRecord)
              -> std::result::Result<(), Box<std::error::Error + Sync + Send>> {

        ANDROID_LOGGER.log(record);
        Ok(())
    }
}
```

**Comment by Nercury** [comment]
Hey, it's all good! Please review https://github.com/Nercury/android_logger-rs/pull/6, where I reintroduced your change and renamed `PlatformLogger` to `AndroidLogger`.

There was a reason for *not* exposing `AndroidLogger`. On android, the activity can be created many times (this is where a logger would be initialised), however the stuff initialised in native memory can stay (i.e. the logger). The `init_once` communicates that hey, on second attempt the failure is expected (logger is already initialised). Therefore if you use `AndroidLogger` directly, your framework should handle this instead.

> I have a similar sentry appender implementation but I haven't decided which is better:
> 1. add Append implementation in separate crates such as android_logger-rs or sentry
> 2. add Append implementation of different crates directly in log4rs

There is a third option (3): crate android-logger-log-rs, but I guess this might be an overkill. However, it would be great if the framework allowed to add log backends easily (3), while simultaneously providing different "built-in" backends (1) itself. I prefer to avoid adding (2) any more dependencies to this crate.

**Comment by Dushistov** [comment]
>add Append implementation in separate crates such as android_logger-rs or sentry
>add Append implementation of different crates directly in log4rs
>There is a third option (3): crate android-logger-log-rs

Why not, just add crate feature with name like `support-log4rs` and if feature is set export
`AndroidLogger` and `log4rs` should handle all other stuff by itself?

**Comment by Nercury** [comment]
> Why not, just add crate feature with name like support-log4rs and if feature is set export
> AndroidLogger and log4rs should handle all other stuff by itself?

Looks a bit complicated, let's keep it simple and export this symbol for all.

**Comment by king6cong** [comment]
>  (3): crate android-logger-log-rs

That's also a viable option :)

Since what we want to do is to building an logger environment around log4rs, I would also like to hear from @sfackler

**Pull request merged**
